### ISSUE TITLE
dataset 'About' menu item

### ISSUE THREAD

**Issue by acthp** [acthp/ucsc-xena-client#11]
Should take us to dataset details.

**Comment by achang28** [comment]
Had a discussion w/ Jing.  Will the implementation within Dev follow Production's implementation:  have the Dataset details page use parameters that are provided by the constructed URL, e.g. `https://genome-cancer.soe.ucsc.edu/proj/site/xena/datapages/?dataset=public%2Fother%2F1000_genomes%2FBRCA1&host=https%3A%2F%2Fgenome-cancer.ucsc.edu%3A443%2Fproj%2Fpublic%2Fxena`?

**Comment by acthp** [comment]
yes, should work the same way. The parameters are encoded in the dataset
id. This was a wonky work-around for the problem that javascript has no
proper map type: you can't use an object as a key in a map. Our datasets
have a name and a host, like

{name: <string>, host: <string>}

So to make a js map of datasets we have to convert that to a string
somehow. We ended up just JSON stringifying it, rather than using some
other convention, like name::host, or whatever.

So in the column prop there should be a dsID which is a JSON encoded object
with name & host. So, the link is built by parsing it out & using them as
the dataset & host params.

**Comment by jingchunzhu** [comment]
fixed in 48ebd23
