### ISSUE TITLE
Dataset drop down menu: hub name isn't in correct place

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#17]
It should be at the top of the list of datasets from that hub but instead it looks like it's appearing in alphabetical order

**Comment by achang28** [comment]
Just "repositioned" the sorting logic so that the server name (e.g. "hud name") is back to being the item to be listed in the Dataset drop-down.  The fix will pushed to in the next dev update.

**Comment by achang28** [comment]
Many fixes, updates, and the fix for this particular issue has been updated in current 'dev' repository.

**Comment by maryjgoldman** [comment]
Looks good!
