### ISSUE TITLE
Disable cohort and filter drop down when in chart mode

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#18]
Otherwise people can change it but then they're still viewing the old data in the chart

**Comment by achang28** [comment]
Waiting to see what response you and/or Jing provides for "Chart Analysis View" mockup in Balsamiq...

**Comment by maryjgoldman** [comment]
We will push this release to production before we finish implementing the mock ups. Thus, this will still need to be done no matter what is resolved in the Balsamiq mock ups.

**Comment by achang28** [comment]
Just to be sure, the "Samples In" menu selection should remain as a drop down menu?  (It doesn't appear do anything...)

![appcontrols](https://cloud.githubusercontent.com/assets/3760499/13337395/fa100a58-dbcf-11e5-83c9-3c92c5bf3423.png)

**Comment by maryjgoldman** [comment]
Every sample has Phenotype data. Try a cohort where not every sample has data (I'm pretty sure all the samples have data in all the datasets for that particular cohort). Try the example below instead.
![untitled](https://cloud.githubusercontent.com/assets/13877333/13337841/a7536ad2-dbd2-11e5-9a75-2875527aa896.png)

**Comment by achang28** [comment]
@maryjgoldman Just went off your example -- I see how it effects the column data, and the sample quantity, e.g. n=xxxx.  In my previous question, I forgot to show/specify that I was referring to the Chart portion -- no matter which dataset I choose for the Samples, the chart is not effected in any way.

Sorry about the omission...

**Comment by maryjgoldman** [comment]
Ah, I see what you're saying. Yes, the filter is not being applied to the Chart. Do you want to file a bug or should I?

**Comment by maryjgoldman** [comment]
Actually, this is not a bug with filters. Right now in production we disable filtering when in chart mode. We should do the same here. Expanding this issue ...

**Comment by acthp** [comment]
Fixed via ceff53e923d31a7e9bf1d810b71999c7d94abb3d
