### ISSUE TITLE
FF only issues: download and sort don't work

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#21]
Also, might be nice to have slightly better CSS. It's not terrible, but it is using up a lot of extra white space.

**Comment by acthp** [comment]
Sort resolved via e1b9d944e047af612b93d5bc8e56fbfef922917e

**Comment by achang28** [comment]
@maryjgoldman -- go ahead and update/pull `dev` from Github, and try the download from Firefox.

**Comment by maryjgoldman** [comment]
Download and sort now both work in FF
