### ISSUE TITLE
tooltip on coded feature throwing errors

### ISSUE THREAD

**Issue by acthp** [acthp/ucsc-xena-client#28]
row.map is not a function

**Comment by achang28** [comment]
For my own reference, example dataset to produce the errors would be **Phenotype**, along with a view of "**gender**", which yields non-numerical values vs. numerical values.

**Comment by acthp** [comment]
The bug is in the nn() call, line 157. nn() is filtering out ```null``` & ```undefined```, but the expression passed ```(val !== 'NA' && !code) && ...``` is actually a boolean ```false```, or a row. So nn() needs to filter ```false```.

That whole expression looks wonky. I'm sure there's a simpler solution. For now, changing nn() to check ```false``` should work.

**Comment by achang28** [comment]
Thanks for the breakdown.  I see the nn() invocation.  Testing it out...

**Comment by jingchunzhu** [comment]
fixed in c21db38171
