### ISSUE TITLE
need KM warning on duplicate sample

### ISSUE THREAD

**Issue by acthp** [acthp/ucsc-xena-client#29]

**Comment by jingchunzhu** [comment]
There is the ! icon on the right of p value
![image](https://cloud.githubusercontent.com/assets/999493/13311270/de3c5126-db41-11e5-8054-9fb8c1339fc2.png)

**Comment by acthp** [comment]
That's a placeholder: hard-coded string.

**Comment by acthp** [comment]
Fixed with 94ea81c9c5a4e6dfa144b1e398567ce0df24ad3a
