### ISSUE TITLE
Make column resize more prominent

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#31]
Right now it's hard to know a) it's there and b) click on it.

**Comment by achang28** [comment]
@maryjgoldman Let's go over this when you're free tomorrow (5/29).  Don't think I understand the specific area that you're referring to.

**Comment by achang28** [comment]
@maryjgoldman By any chance is this other issue one-and-the-same as this one:  https://github.com/acthp/ucsc-xena-client/issues/14 ?

**Comment by maryjgoldman** [comment]
No, #14 is to help the user get a feel of how much they have dragged the column once they've clicked on it. This one is about helping the user know to click on it in the first place. Right now, a new user would have no idea a) that it was there and b) even if they knew you could resize the columns, where to look for the 'active area'

**Comment by acthp** [comment]
Fixed via c53ea6bf4ce0089f1d398d0f5bb549da4bbfa0dc
