### ISSUE TITLE
column doesn't update with new data if you relax a filter

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#33]
To reproduce:
TCGA BRCA
Add gene expression (illuminahiseq), TP53
Filter samples to those in gene expression (agilent)
Add gene expression (illuminahiseq), TP53 (same as before)
Now filter samples to those in gene expression (illuminahiseq)
Observe grey data
![untitled](https://cloud.githubusercontent.com/assets/13877333/13338539/dabe5900-dbd6-11e5-8bc7-6ab47c37b87f.png)

**Comment by acthp** [comment]
This is due to the widget data fetch not being re-run after changing samples-from.

**Comment by acthp** [comment]
Fixed via 625f51fdacb9c9613d04eab51e726caee7be5ade
