### ISSUE TITLE
dataset drop down: put data from local hub first

### ISSUE THREAD

**Issue by maryjgoldman** [acthp/ucsc-xena-client#35]
Right now it's listed at the bottom. Put it at the top instead

**Comment by achang28** [comment]
@maryjgoldman Can you show, or explain to me, which of the listings are coming from local hub?

**Comment by maryjgoldman** [comment]
Right now the datasets from the local hub are listed at the bottom of the list, after the ones from the main hub (the one from UCSC). I would like they to be listed at the top instead.

If you don't have your own local hub running, then you won't see any datasets from the local hub at the bottom of the list. If you install the local xena hub and add in a few datasets, you'll see it listed at the bottom.

**Comment by maryjgoldman** [comment]
I'm still seeing this on my production build. Did it maybe not get into the build yet?

**Comment by jingchunzhu** [comment]
I should be in production.   

npm install  (did you do this?)
npm run start:prod

**Comment by maryjgoldman** [comment]
I did npm install and npm run start:prod and am in a new tab. Still see the datasets from my local hub at the bottom of the list. Git pull says I'm completely up-to-date.

**Comment by maryjgoldman** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13877333/13579557/03f7eaf0-e453-11e5-8927-ef5393b9b5c9.png)

**Comment by jingchunzhu** [comment]
can you click on "data hubs" page? what do you see?

**Comment by maryjgoldman** [comment]
If I go to the data hubs page first, then it is in the right order in drop down. If I let the client automatically connect to my local hub, then it's at the bottom

**Comment by jingchunzhu** [comment]
I see. I need to also fix the default order in the store.js in the client code.

**Comment by jingchunzhu** [comment]
fixed in 57a38f

**Comment by maryjgoldman** [comment]
Looks good now
