### ISSUE TITLE
KmPlot renders error screen (TCGA > PANCAN12 > Phenotypes > Gender)

### ISSUE THREAD

**Issue by achang28** [acthp/ucsc-xena-client#46]
Specifically with the parameters from the image below, getting a "red-screen-of-death" screen for KmPlot modal.

![column_params](https://cloud.githubusercontent.com/assets/3760499/13437195/c935a084-df97-11e5-80d5-670ca43bccbc.jpg)
![error_screen](https://cloud.githubusercontent.com/assets/3760499/13437196/ca98b3d0-df97-11e5-8ffd-9adf9cef15af.jpg)

**Comment by achang28** [comment]
@acthp The furthest I have gotten in my research, and understanding, is that the state object passed to most -- if not all -- of the callbacks (provided to the functions within appSelector.js), has it's grandchild "gender" array containing an element with an empty string, which is not matching upwith the "groupIndeces" object within js/models/km.js.

js/appSelector.js
![appselector_inspector](https://cloud.githubusercontent.com/assets/3760499/13440703/36a425a4-dfa8-11e5-96f9-b1fe0a26ff7a.jpg)

js/models/km.js
![km_inspector](https://cloud.githubusercontent.com/assets/3760499/13440709/3aeb584e-dfa8-11e5-897a-227106dda854.jpg)

**Comment by maryjgoldman** [comment]
This works on production. Also works on coded features from the same cohort as well as from the PanCan cohort (i.e. is not a problem with large cohorts). Also works on continuous features from the same cohort.

**Comment by acthp** [comment]
Fixed via 5dc94a9a591a6c362799809a6a995ad437876936.
