### ISSUE TITLE
Some data points from Column Plot yield errors

### ISSUE THREAD

**Issue by achang28** [acthp/ucsc-xena-client#50]
**Cohort**:  TCGA Esophageal Cancer (ESCA)
**Dataset**:  somatic mutation SNPs and small INDELs (ucsc automated vcf)
**Gene**:  TP53
__________________________________________________________________________________
![column_display](https://cloud.githubusercontent.com/assets/3760499/13448520/bbb34b28-dfd8-11e5-8733-778edb26a80b.png)
![error_msg](https://cloud.githubusercontent.com/assets/3760499/13448521/bdbc0694-dfd8-11e5-9681-da5b9a2061a2.png)

**Comment by achang28** [comment]
Line 34 of js/Tooltip.js has the following array contents.  Notice the 2nd index within the array...

![array](https://cloud.githubusercontent.com/assets/3760499/13448819/de554b48-dfda-11e5-8001-30584aca36e7.png)

**Comment by acthp** [comment]
Fixed via 375cfb257fc8c2f898a07e6e883869325c41809e
